### ISSUE TITLE
ENH: Minor fixes to add

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#609]
Just so I don't forget, from #607 

- [x] fix enumeration of example capabilities, https://mne.tools/mne-bids-pipeline/examples/ds003104.html should not have time-by-time decoding: #606
- [x] Add proj joint plots to report using ECG/EOG Epochs: #614
- [x] cache `freesurfer/_02_coreg_surfaces.py`: #615
- [x] cache `_01_make_bem_surfaces.py` steps by dealing with recomputation params properly: #615
- [x] cache `_03_make_cov.py`: #615
- [x] cache `_02_make_forward.py` by splitting `trans` step out separately (maybe?): #616, #618
- [x] cache `_04_make_inverse.py`: #618
- [x] Fix `config.*` use inside functions, or at least ensure caching is not broken with them: #635
- [x] Use `return_candidates=True` in `find_empty_room` if available: #524 #642
- [x] cache report: #652
- [x] Add coverage: #658
- [x] cache `source/_99_group_average.py`: #765
- [x] cache `sensor/_99_group_average.py`: #765
- [x] Add re-run test checks on CircleCI: #765

**Comment by hoechenberger** [comment]
@SophieHerbst had an aborted epochs run; after restarting the step, it seems that epochs for all subjects were being re-created – not only those for subjects that were not processed before. Is that a known limitation?

**Comment by hoechenberger** [comment]
I believe she had debug mode turned on, i.e., `on_error = "debug"`. Not sure if this is relevant or not

**Comment by hoechenberger** [comment]
@larsoner We should cut a new release with those fixes. As far as I know, @SophieHerbst uses stable, installed following our instructions on the website

**Comment by hoechenberger** [comment]
@larsoner I tagged a new release:
https://github.com/mne-tools/mne-bids-pipeline/releases/tag/v1.2.0

Waiting for it to land on PyPI and conda-forge.

**Comment by larsoner** [comment]
Have you waited for it to finish, then re-run it? I'd expect it to re-run some stuff once between mne-bids-pipeline version jumps

**Comment by larsoner** [comment]
>  Should I rerun the whole pipeline from scratch after each update?

You shouldn't have to. But I wouldn't be surprised if some steps re-ran once (seemingly unnecessarily) after an update. That's why I was trying to ask if you tried running *twice* after the update -- I'd expect a re-run once but the second time you run it it should cache. If it doesn't, it seems like a bug.

But to be safest I'd just re-run the whole pipeline after an update. Then everything should be up to date...

**Comment by SophieHerbst** [comment]
ok, doing first complete re-run after the update. I will try a second time after and keep you posted.

**Comment by SophieHerbst** [comment]
While I am still waiting for the re-run to finish (I have a lot of runs): it would be helpful if the version of the bids-pipeline used per step was to be found in the output for reporting in a paper and replicability. Is this currently the case?

**Comment by SophieHerbst** [comment]
I see the MNE version there, but not the version of the bids-pipeline

**Comment by SophieHerbst** [comment]
@larsoner I confirm: first run after update re-runs some steps, 2nd run after update does not, cashing is fast as expected

**Comment by hoechenberger** [comment]
> cashing is fast as expected

I had to take a double-take here as I kept reading "crashing as fast as expected" 😅😂
